### ISSUE TITLE
Based on OAuth 1-legged specification oauth_token should be included in the header and added to the signature base string

### ISSUE THREAD

**Issue by akalcik** [rhargreaves/oauth-dotnetcore#10]
Based on [OAuth 1-legged specification](http://oauthbible.com/#oauth-10a-one-legged) _oauth_token_ should be included in the header and added to the signature base string.

**Comment by rhargreaves** [comment]
As I understand it, your pull request appears to be adding functionality to handle blank/empty string `oauth_token`s in such a way to include them in the header.

https://tools.ietf.org/html/rfc5849#appendix-A adds the amendment:

> o  Allowed omitting the "oauth_token" parameter when empty.

As such, I don't believe it's required for `oauth_token=""` to be provided in the header when its empty.

**Comment by akalcik** [comment]
Well without to set the _oauth_token_ as an empty string I'm not able to make request again Jira, which claims to use OAuth 1.0a. But I implemented it in the #12 so that when you set _null_ than the _oauth_token_ is omited.

**Comment by rhargreaves** [comment]
OK I understand. I'll accept this in but I'll probably have to release it as a major version increment as I believe it has the potential to break existing implementations that might assume an empty string value would result in `oauth_token` not being included.

**Comment by rhargreaves** [comment]
Would you mind doing a pull request that only includes the fix for this issue?

**Comment by akalcik** [comment]
> Would you mind doing a pull request that only includes the fix for this issue?

 That was also my intention don‘t know why this happened. I‘ll undo the PR and start them again.

**Comment by akalcik** [comment]
Ok  I see, because I worked over my dev branch and wanted the to see the whole integration. I'll try it so split it.

**Comment by akalcik** [comment]
Updated PR to only include fix for specific issue in #12

**Comment by rhargreaves** [comment]
Great! I'll merge this one in after we resolve https://github.com/rhargreaves/oauth-dotnetcore/issues/8. I'd like to merge that one in first as I can release that as a minor change before proceeding with this larger, major change.

**Comment by akalcik** [comment]
When you accept all PRs (if you mind to do so) I would like also update documentation.
