### ISSUE TITLE
Query string parsing is wrong

### ISSUE THREAD

**Issue by akalcik** [rhargreaves/oauth-dotnetcore#8]
```csharp
OAuthRequest client = OAuthRequest.ForProtectedResource(OAuthSignatureMethod.RsaSha1.ToString(),
consumerKey, privateKeyAsXml, string.Empty, null);
client.RequestUrl = $"https://www.url.com/search?jql=assignee=ZZAVAKAA&user_id=ZZAVAKAA";
string authorizationHeader = client.GetAuthorizationHeader();
```

When I call the code above I get the exception _Uri does not have valid query string_ which is wrong as the query above is a valid query string.

See the output when I parse the query with the help of ```HttpUtility.ParseQueryString```

```csharp
var queryValues = HttpUtility.ParseQueryString("https://www.url.com/search?jql=assignee=ZZAVAKAA&user_id=ZZAVAKAA");
queryValues.Dump();
```

Key | Value
-- | --
https://www.url.com/search?jql | assignee=ZZAVAKAA
user_id | ZZAVAKAA

**Comment by rhargreaves** [comment]
According to https://tools.ietf.org/html/rfc3986#section-3.4 and https://tools.ietf.org/html/rfc3986#section-2.2 the query `jql=assignee=ZZAVAKAA&user_id=ZZAVAKAA` is not valid as a query string. The equals sign is defined as a reserved character so should be escaped as follows:

`jql=assignee%3DZZAVAKAA&user_id=ZZAVAKAA` 

Further more `HttpUtility.ParseQueryString()` accepts a query string as an argument, but not a full URL so the output you give as an example is not valid. See https://docs.microsoft.com/en-us/dotnet/api/system.web.httputility.parsequerystring?view=netframework-4.8

**Comment by akalcik** [comment]
So you propose to escape the query string like this before to set it as request url?  ```jql=assignee%3DZZAVAKAA&user_id=ZZAVAKAA```

> Further more HttpUtility.ParseQueryString() accepts a query string as an argument, but not a full URL so the output you give as an example is not valid. 

This argument I don't understand can you explain it little bit more in detail?

**Comment by akalcik** [comment]
I validated it now by using old method implementation. When I construct the query like this ```jql=assignee%3DZZAVAKAA&user_id=ZZAVAKAA``` and send it over the wire I get response code 401 which indicates that the signature is invalid. I don't have this behavior by my implementation.

**Comment by rhargreaves** [comment]
After re-reading RFC 3986, I see that the equals sign is fine to not be percent-encoded, so you are right that it should be allowed. 

However, your implementation not only fixes this bug but also adds some additional untested functionality. Please could you remove the checking of HTTP scheme and and the disallowing of zero query string parameters?

Please also remove `[TestCase("https://www.url..com")]` as I don't believe it to be relevant for a function that only cares about the query string parameters. You may leave the null check in though!  🙂

> This argument I don't understand can you explain it little bit more in detail?

Your use of `HttpUtility.ParseQueryString()` is resulting in an undefined output. `ParseQueryString` according to the MSDN page is supposed to take just a query string (e.g. `a=1&b=2`) not the whole URL (e.g. `http://foo.com/?a=1&b=2`). The usage you show results in the first entry of the `NameValueCollection` containing the HTTP scheme and host in addition to the first query parameter name, which is incorrect.

**Comment by akalcik** [comment]
Should I go with the ```UriFormatException``` or with```ArgumentException``` as before?

**Comment by rhargreaves** [comment]
I'd just remove the checking on the number of query string parameters/contents of `Uri.Query` entirely. The exception thrown from the original code (https://github.com/rhargreaves/oauth-dotnetcore/blob/master/src/OAuth/WebUtils.cs) isn't relevant if we're just going to be using `HttpUtility.ParseQueryString` to extract the query parameters and values. I don't see the value in throwing either of those `ArgumentException`s so let's just remove them.

In many ways we should just ditch the `WebUtils` class and use `HttpUtility.ParseQueryString` from the .NET Framework. However, for now, let's just keep `WebUtils` as a wrapper to maintain the interface. It's a smaller change and solves your original problem.

**Comment by akalcik** [comment]
Could you show me what do you mean?

**Comment by rhargreaves** [comment]
Basically https://github.com/rhargreaves/oauth-dotnetcore/commit/403b50aa669e1787af1529695952bb70fba071e9

**Comment by rhargreaves** [comment]
I'll merge your changes in and apply my commit over them.

**Comment by rhargreaves** [comment]
Thanks for your contribution! 😁

**Comment by rhargreaves** [comment]
Published https://www.nuget.org/packages/OAuth.DotNetCore/2.2.0

**Comment by akalcik** [comment]
Well you didn't accepted  PR #11 so the #14 is incorrect.
